use vanguard_agent::SevenDimensionsInsight;
use chrono::Utc;

pub struct ReportGenerator;

impl ReportGenerator {
    pub fn new() -> Self {
        Self
    }

    /// 生成符合 FBE 规范的标准 Markdown 洞察报告
    pub fn generate_markdown(&self, customer_name: &str, engagement_type: &str, insight: &SevenDimensionsInsight) -> String {
        let now = Utc::now().format("%Y-%m-%d %H:%M:%S UTC").to_string();
        
        let mut report = format!(
r#"# 🛡️ FBE 客户洞察与需求挖掘报告 — {customer_name}

> **生成时间**：{now}  
> **事务类型**：{engagement_type}  
> **分析引擎**：Vanguard FBE Intelligence Engine (Gemini 2.5 Pro)

---

## 📌 一、执行摘要 (Executive Summary)
本报告基于前线部署工程师 (FBE) 采集的现场第一手访谈记录、架构速记与技术交流素材，由 Vanguard AI Agent 自动进行 **Seven Dimensions (七维度需求挖掘模型)** 深度推断与隐性诉求萃取，旨在为后续架构落地、PoC 推进及生产交付提供精准指引。

---

## 🎯 二、七维度需求分析矩阵 (Seven Dimensions Matrix)

### 1. 显性功能诉求 (Functional Requirements)
"#
        );

        if insight.functional.is_empty() {
            report.push_str("- *暂无明显显性功能描述*\n");
        } else {
            for item in &insight.functional {
                report.push_str(&format!("- **[功能]** {}\n", item));
            }
        }

        report.push_str("\n### 2. 核心痛点卡点 (Pain Points)\n");
        if insight.pain_points.is_empty() {
            report.push_str("- *未识别到阻塞级痛点*\n");
        } else {
            for item in &insight.pain_points {
                report.push_str(&format!("- ⚠️ **[痛点]** {}\n", item));
            }
        }

        report.push_str("\n### 3. 待办任务框架 (Jobs to Be Done - JTBD)\n");
        if insight.jobs_to_be_done.is_empty() {
            report.push_str("- *暂无核心待办任务*\n");
        } else {
            for item in &insight.jobs_to_be_done {
                report.push_str(&format!("- 🎯 **[JTBD]** {}\n", item));
            }
        }

        report.push_str("\n### 4. 隐性潜在欲望 (Latent Desires)\n");
        if insight.latent_desires.is_empty() {
            report.push_str("- *未捕获到深层隐性欲望*\n");
        } else {
            for item in &insight.latent_desires {
                report.push_str(&format!("- ✨ **[隐性诉求]** {}\n", item));
            }
        }

        report.push_str("\n### 5. 情绪心理诉求 (Emotional Needs)\n");
        if insight.emotional_needs.is_empty() {
            report.push_str("- *未记录特殊情绪期望*\n");
        } else {
            for item in &insight.emotional_needs {
                report.push_str(&format!("- 💡 **[心理期望]** {}\n", item));
            }
        }

        report.push_str("\n### 6. 组织与社交属性 (Social & Organizational Needs)\n");
        if insight.social_needs.is_empty() {
            report.push_str("- *未涉及跨组织属性*\n");
        } else {
            for item in &insight.social_needs {
                report.push_str(&format!("- 🤝 **[组织诉求]** {}\n", item));
            }
        }

        report.push_str("\n### 7. 合规与约束边界 (Constraints & Boundaries)\n");
        if insight.constraints.is_empty() {
            report.push_str("- *无明确技术/制度约束*\n");
        } else {
            for item in &insight.constraints {
                report.push_str(&format!("- 🔒 **[约束边界]** {}\n", item));
            }
        }

        report.push_str(
r#"
---

## 🚀 三、FBE 行动项与技术推进建议 (Actionable Recommendations)
1. **架构与基础设施对齐**：根据约束边界，优先完成内网隔离与环境依赖初始化。
2. **快速打通核心 JTBD**：在随后的 PoC 阶段重点演示针对痛点卡点的解决成效。
3. **安全与权限审计**：将关键生产变更与双因素 (2FA/TOTP) 认证策略纳入标准交付规范。

---
*Generated by Vanguard — The FBE Intelligence Platform*
"#
        );

        report
    }

    /// 生成带现代深色样式的 HTML 报告版本
    pub fn generate_html(&self, customer_name: &str, engagement_type: &str, insight: &SevenDimensionsInsight) -> String {
        let md = self.generate_markdown(customer_name, engagement_type, insight);
        
        format!(
r#"<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <title>FBE 客户洞察报告 - {}</title>
  <style>
    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: #0b0f19;
      color: #f1f5f9;
      line-height: 1.6;
      padding: 40px 20px;
      margin: 0;
    }}
    .container {{
      max-width: 800px;
      margin: 0 auto;
      background: rgba(15, 23, 42, 0.85);
      border: 1px solid rgba(255, 255, 255, 0.1);
      border-radius: 16px;
      padding: 32px;
      box-shadow: 0 10px 30px rgba(0,0,0,0.5);
    }}
    h1 {{ color: #38bdf8; border-bottom: 1px solid rgba(255,255,255,0.1); padding-bottom: 12px; }}
    h2 {{ color: #818cf8; margin-top: 24px; }}
    h3 {{ color: #cbd5e1; }}
    ul {{ padding-left: 20px; }}
    li {{ margin-bottom: 8px; }}
    blockquote {{
      background: rgba(56, 189, 248, 0.1);
      border-left: 4px solid #38bdf8;
      padding: 8px 16px;
      margin: 16px 0;
      border-radius: 4px;
    }}
    hr {{ border: 0; height: 1px; background: rgba(255,255,255,0.1); margin: 24px 0; }}
  </style>
</head>
<body>
  <div class="container">
    <pre style="white-space: pre-wrap; font-family: inherit;">{}</pre>
  </div>
</body>
</html>"#,
            customer_name,
            md
        )
    }
}

impl Default for ReportGenerator {
    fn default() -> Self {
        Self::new()
    }
}
