[package]
name = "vanguard-api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
vanguard-auth = { path = "../vanguard-auth" }
vanguard-ingest = { path = "../vanguard-ingest" }
vanguard-agent = { path = "../vanguard-agent" }
vanguard-rag = { path = "../vanguard-rag" }
vanguard-report = { path = "../vanguard-report" }
tokio-stream = { version = "0.1", features = ["sync"] }
futures = "0.3"
uuid = { workspace = true }
tower-http = { version = "0.7.0", features = ["fs"] }
vanguard-tools = { version = "0.1.0", path = "../vanguard-tools" }
vanguard-llm = { version = "0.1.0", path = "../vanguard-llm" }
sqlx = { workspace = true }
chrono = { workspace = true }
